cnc_finray:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.DoubleTowerPoseEstimationDataset
    data_dir: data/FoundationTactile/cnc/cnc_Finray
    encoder_domain: finray
    decoder_domain: pose_estimation_3d
    random_resize_crop: false
    random_hv_flip_prob: 0.0
    color_jitter: null
    pose_dim: 3
    img_norm:
      mean: [0.01000, 0.04490, 0.07897]
      std: [0.06394, 0.14283, 0.20100]
    label_norm:
      mean: [0.0, 0.0, 0.0]
      std: [1., 1., 1.]

cnc_finray2:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.DoubleTowerPoseEstimationDataset
    data_dir: data/FoundationTactile/cnc/cnc_Finray2
    encoder_domain: finray
    decoder_domain: pose_estimation_3d
    random_resize_crop: false
    random_hv_flip_prob: 0.0
    color_jitter: null
    pose_dim: 3
    img_norm:
      mean: [0.00139, 0.02078, 0.10659]
      std: [0.01877, 0.10335, 0.23180]
    label_norm:
      mean: [0.0, 0.0, 0.0]
      std: [1., 1., 1.]

cnc_wedge:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.DoubleTowerPoseEstimationDataset
    data_dir: data/FoundationTactile/cnc/cnc_Wedge
    encoder_domain: wedge
    decoder_domain: pose_estimation_3d
    random_resize_crop: false
    random_hv_flip_prob: 0.0
    color_jitter: null
    pose_dim: 3
    img_norm:
      mean: [0.24580, 0.30085, 0.35867]
      std: [0.18356, 0.14779, 0.18460]
    label_norm:
      mean: [0.0, 0.0, 0.0]
      std: [1., 1., 1.]