cnc_densetact:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.SingleTowerClassificationDataset
    label_process_func: t3.task_utils.process_cnc_cls_label
    data_dir: data/FoundationTactile/cnc/cnc_DenseTact
    encoder_domain: densetact
    decoder_domain: cls_cnc
    random_resize_crop: true
    random_hv_flip_prob: 0.5
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.5
      hue: 0.3
    img_norm:
      mean: [0.20997, 0.28465, 0.26797] 
      std: [0.29838, 0.36981, 0.33362]