cnc_densetact:
  activate: true
  eval_only: false
  data_loader:
    _target_: t3.data_loader.DoubleTowerPoseEstimationDataset
    data_dir: data/FoundationTactile/cnc/cnc_DenseTact
    encoder_domain: densetact
    decoder_domain: pose_estimation_3d
    random_resize_crop: false
    random_hv_flip_prob: 0.0
    color_jitter: null
    pose_dim: 3
    img_norm:
      mean: [0.20997, 0.28465, 0.26797] 
      std: [0.29838, 0.36981, 0.33362]
    label_norm:
      mean: [0.0, 0.0, 0.0]
      std: [1., 1., 1.]